### ISSUE TITLE
WebSocket connection to 'wss://f.xmrminingproxy.com:8181/' failed:

### ISSUE THREAD

**Issue by xcoders-hub** [NajmAjmal/monero-webminer#1]

**Comment by NajmAjmal** [comment]
Hi @xcoders-hub,

Are you using a VPN or proxy whilst using this?

Thanks, Najm

**Comment by NajmAjmal** [comment]
Hi @xcoders-hub

I have changed the miner proxy, it should work now

If it still doesn't work, re-open this issue or create another

Thanks, Najm

**Comment by Coll147** [comment]
Hello, I am having this problem similar to the one in the thread with the webminer, does anyone know how to solve it?
![image](https://github.com/NajmAjmal/monero-webminer/assets/91793263/03b02d1b-152c-4521-b1ac-99c1786da65d)

**Comment by tsunamioffreedom** [comment]
same issue

**Comment by NajmAjmal** [comment]
Fixed https://github.com/NajmAjmal/monero-webminer/pull/18
