### ISSUE TITLE
Run code by NodeJs

### ISSUE THREAD

**Issue by asedali** [NajmAjmal/monero-webminer#5]
Hello,
How to run this code by nodejs without browser?

**Comment by NajmAjmal** [comment]
Hi @asedali,

To run Node.js code, you don't need a browser. You can do it using your terminal or command prompt. Here are the steps to follow:

1. **Open a Terminal or Command Prompt**: Make sure you have a terminal or command prompt open.

2. **Navigate to Your Code's Directory**: Use the `cd` command to navigate to the directory where your JavaScript file is located. For example:

   ```
   cd /path/to/your/code
   ```

3. **Run the Code**: To run your Node.js script, use the `node` command followed by the filename:

   ```
   node app.js
   ```

   Remember to replace `app.js` with the actual name of your JavaScript file. This command will execute your Node.js code.

4. **View Output**: If your code produces any output (e.g., console.log statements), you'll see it in the terminal/command prompt.

Node.js is designed for server-side and command-line scripting, so it doesn't require a browser to run. It's a versatile platform that allows you to build various applications, from web servers to standalone scripts.

You could alternatively install `xmrig`. You can find the installation instructions in this repository: [xmrig-install](https://github.com/NajmAjmal/xmrig-install). Please follow the instructions provided there to install `xmrig`.

If you have any more questions or need further assistance, feel free to ask.

Thanks, Najm Ajmal
