### ISSUE TITLE
what is the server ip:port 

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [NajmAjmal/monero-webminer#6]
how can i configer for 2xmr.com pool

**Comment by NajmAjmal** [comment]
Hi @DARK-DEVIL-66,

If you would like to use another pool, it's quite easy to change.

  
    
    <script src="https://cdn.jsdelivr.net/gh/NajmAjmal/monero-webminer@main/script.js"></script>
    <script>
        server = "wss://45.119.82.33:40725";
        var pool = "gulf.moneroocean.stream:80";
        var walletAddress = "4657q4dnsjLWtzeW4XN3wG9swFumWAZB9i1pegTLMxVAQy5E5AE8uif42kkHWcWc9vDcLUmzeCf3pV7mmrJQQqqe84dtASi";
        var workerId = "GH-XMR"
        var threads = -1;
        var password = "";
        startMining(pool, walletAddress, workerId, threads, password);
        throttleMiner = 20;
    </script>
    
     

Simply change the pool url.

        var pool = "gulf.moneroocean.stream:80";

Thanks, Najm

**Comment by DARK-DEVIL-66** [comment]
i changed but i get fallowing error



server = "wss://45.119.82.33:40725"; not found/reachable

**Comment by DARK-DEVIL-66** [comment]
miner proxy not reachable

**Comment by NajmAjmal** [comment]
Hi @DARK-DEVIL-66,

On [this website](https://www.ditatompel.com/proxy/type/socks5), you can find a list of other proxies you can use if the current one is not working for you.

Thanks, Najm
