### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by adityathakare1** [NajmAjmal/monero-webminer#8]
![Screenshot_20231107-170116_Kiwi Browser](https://github.com/NajmAjmal/monero-webminer/assets/94916813/3832249c-6638-40e9-a8a2-3c756e729388)

**Comment by adityathakare1** [comment]
Can it run without websock

**Comment by NajmAjmal** [comment]
Hi @adityathakare1,

On [this website](https://www.ditatompel.com/proxy/type/socks5), you can find a list of other proxies you can use if the current one is not working for you.

Thanks, Najm

**Comment by tsunamioffreedom** [comment]
can i just use any proxy from that website? does it not need a connection to the pool or something?

**Comment by tsunamioffreedom** [comment]
because i tried many and none work for me, always the same error

**Comment by tsunamioffreedom** [comment]
and can you please explain the purpose if this variable (`server`)

**Comment by tsunamioffreedom** [comment]
@NajmAjmal
