### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [NajmAjmal/monero-webminer#9]
i tryed too many times but not working

it's support 2miners.com xmr minng

**Comment by DARK-DEVIL-66** [comment]
it's my wallet address so please configer for me 



4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC

**Comment by NajmAjmal** [comment]
Hi @DARK-DEVIL-66,

I have configured your details [here](https://github.com/NajmAjmal/monero-webminer/tree/DARK-DEVIL-66). You will need to configure the pool since i can't find it online. Perhaps leave a link to the pool website.

Thanks, Najm

**Comment by DARK-DEVIL-66** [comment]
it's configred gulf.moneroocean.stream:80 so i need it for this pool bro https://xmr.2miners.com/help

**Comment by NajmAjmal** [comment]
Configured Pool: https://github.com/NajmAjmal/monero-webminer/commit/18f06b96059ace0d6eeecdb395d7716c3ecbb176
